version: "3"
services:
  postgres:
    image: postgres
    container_name: db_postgres_account
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: account
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - .data/docker/postgres:/var/lib/postgresql/data
